---
title: "Relatório Anual"
author: "JoseHugo"
date: "07/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r dados}
#Libraries
library(dplyr)
library(lubridate)
library(ggplot2)
#Tabelas e manipulações
bd<-read.csv("C:/Users/AllanaNunes/Desktop/MARINAUTA/TECNICO/CIA AMBIENTAL/Python/bd_jan22.csv",h=T, sep=";", dec=",")


#Manipulações
bd<-bd[-c(31,32,33,34,35)] #retirando colunas desnecessárias


names(bd)[1:30] <- c("ID1", "ID","Data", "Hora","Mes", "Ano", "Entreposto", "Codigo", "Pescador", "SPP", "Barco","Tipo", "Municipio", "Origem", "Tempo_pesca", "Arte_agrupado", "Arte", "Malha", "Tipo_recurso", "Familia", "Taxon","Nome_popular", "Peso", "Duzia", "Preco", "Pesqueiro", "Regiao", "Befeficiamento","Venda", "Receita") # renomeando colunas

#Data
bd$Data<-dmy(bd$Data)
bd$Receita<-as.numeric(round(bd$Receita, 2))

bd$Peso<-as.numeric(bd$Peso)
bd$Duzia<-as.numeric(bd$Duzia)
bd$Preco<-as.numeric(bd$Preco)

bd$data_extenso<-format(bd$Data, "%B de %Y")

so_mes<-bd$Data[length(bd$Data)]
so_mes<-format(so_mes, "%B")
###Tabelas agrupadas
```


```{r barcos}
## Lista Geral de Embarcações Ativas Registradas por MES

barcos<-bd %>% group_by(Mes=floor_date(Data, "month"), Origem, Barco, SPP) %>% 
  summarise(Atividade = length(ID1[!is.na(ID1)]))
barcos<-filter(barcos, Barco != "S/N - -") #tirando os barcos que não são conhecidos
barcos<-filter(barcos, Barco != "-")#tirando os barcos que não são conhecidos


#Lista Geral de Embarcações Ativas Registradas por ANO
barcos_ano<-bd %>% group_by(Ano=floor_date(Data, "year"), Origem, Barco, SPP) %>% 
  summarise(Atividade = length(ID1[!is.na(ID1)]))
barcos_ano<-filter(barcos_ano, Barco != "S/N - -") #tirando os barcos que não são conhecidos
barcos_ano<-filter(barcos_ano, Barco != "-")#tirando os barcos que não são conhecidos


# n° geral de de barcos por mes

barcos_geral_mes<-barcos %>% group_by(Mes) %>%
  summarize(Barcos_ativos = length(Barco))

# n° feral de barcos por ano

barcos_geral_ano<-barcos_ano%>%group_by(Ano) %>%  summarize(Barcos_ativos = length(Barco))

# numero de barcos por ano em cada comunidade pesqueira

barcos_vila_ano<-barcos_ano%>%group_by(Origem, Ano)%>%
  summarize(Barcos_ativos = length(Barco))

barcos_vila_mes<-barcos%>%group_by(Origem, Mes)%>%
  summarize(Barcos_ativos = length(Barco))


#-------------------

##Lista de barcos por Analise por entreposto

### Lista de barcos por entreposto por MES
barcos_1<-bd %>% group_by(Mes=floor_date(Data, "month"), Origem, Barco, SPP, Entreposto) %>% 
  summarise(Atividade = length(ID1[!is.na(ID1)]))

barcos_1<-filter(barcos_1, Barco != "S/N - -") #tirando os barcos que não são conhecidos
barcos_1<-filter(barcos_1, Barco != "-")#tirando os barcos que não são conhecidos



### Lista de barcos por entreposto a cada ANO
barcos_2<-bd %>% group_by(Ano=floor_date(Data, "year"), Origem, Barco, SPP, Entreposto) %>% 
  summarise(Atividade = length(ID1[!is.na(ID1)]))
barcos_2<-filter(barcos_2, Barco != "S/N - -") #tirando os barcos que não são conhecidos
barcos_2<-filter(barcos_2, Barco != "-")#tirando os barcos que não são conhecidos

## Número de Barcos Ativos em cada entreposto por ano

barcos_entreposto_mes<-barcos_1%>%group_by(Entreposto, Mes) %>%
  summarize(Barcos_ativos = length(Barco))

barcos_entreposto_ano<-barcos_2%>%group_by(Entreposto,Ano) %>%
  summarize(Barcos_ativos = length(Barco))



```








```{r dados gerais}

#Analise por entrepotos
parametros_entreposto_mes<-bd%>% group_by(Entreposto, Mes=floor_date(Data, "month"), ) %>%
   summarise(Desembarques = length(ID1[!is.na(ID1)]), Peso = sum(Peso, na.rm=T), Duzia= sum(Duzia, na.rm=T),  Receita = sum(Receita, na.rm=T))

parametros_entreposto_ano<-parametros_entreposto_mes%>%group_by(Entreposto, Ano=floor_date(Mes, "year"))%>%
  summarise(Desembarques = sum(Desembarques), Peso = sum(Peso, na.rm=T), Duzia= sum(Duzia, na.rm=T),  Receita = sum(Receita, na.rm=T))


#Parametros gerais

parametros_geral_mes<-parametros_entreposto_mes%>%group_by(Mes)%>%
  summarise(Desembarques = sum(Desembarques), Peso = sum(Peso, na.rm=T), Duzia= sum(Duzia, na.rm=T),  Receita = sum(Receita, na.rm=T))


parametros_geral_ano<-parametros_entreposto_mes%>%group_by(Ano=floor_date(Mes, "year"))%>%
  summarise(Desembarques = sum(Desembarques), Peso = sum(Peso, na.rm=T), Duzia= sum(Duzia, na.rm=T),  Receita = sum(Receita, na.rm=T))

#Comunidade
parametros_vila_mes<-bd%>% group_by(Municipio,Origem, Mes=floor_date(Data, "month"), ) %>%
   summarise(Desembarques = length(ID1[!is.na(ID1)]), Peso = sum(Peso, na.rm=T), Duzia= sum(Duzia, na.rm=T),  Receita = sum(Receita, na.rm=T))

parametros_vila_ano<-bd%>% group_by(Municipio,Origem, Ano=floor_date(Data, "year"), ) %>%
   summarise(Desembarques = length(ID1[!is.na(ID1)]), Peso = sum(Peso, na.rm=T), Duzia= sum(Duzia, na.rm=T),  Receita = sum(Receita, na.rm=T))


#compilado gerel
mes_geral<-merge(barcos_geral_mes, parametros_geral_mes, all.x = T, all.y=F)
ano_geral<-merge(barcos_geral_ano, parametros_geral_ano)

#compilado por entreposto

mes_entreposto<-merge(barcos_entreposto_mes, parametros_entreposto_mes, all.y=T)
ano_entreposto<-merge(barcos_entreposto_ano, parametros_entreposto_ano)

# compilado por comunidade pesqueira
mes_vila<-merge(barcos_vila_mes, parametros_vila_mes, all.y=T)
ano_vila<-merge(barcos_vila_ano, parametros_vila_ano)

```



```{r datas}
meses<-unique(bd$data_extenso)

ultimo_mes<-bd$Data[length(bd$Data)]
ultimo_mes<-format(ultimo_mes, "%B")

ultimo_ano<-bd$Data[length(bd$Data)]
ultimo_ano<-format(ultimo_ano,"%Y")

```


```{r GRAFICOS GERAIS}

 library(tidyr)

mes_entreposto$Ano<-floor_date(mes_entreposto$Mes, "year")
mes_entreposto$Ano<-as.factor(mes_entreposto$Ano)
mes_entreposto$Mes<-format(mes_entreposto$Mes, "%m")
mes_entreposto



b<-mes_entreposto[, -c(4:7)]
b
a<-pivot_wider(b, names_from =Ano,  values_from = Barcos_ativos) 


a

comunidades<-read.csv("C:/Users/AllanaNunes/Desktop/comunidades.csv",h=T, sep=";", dec=",")


comunidades


for(i in mes_entreposto$Entreposto){
 print(ggplot(subset(mes_entreposto, Entreposto==i), aes(x=Mes, y=Peso, group= Ano), fill=getPalette(colourCount))+
  geom_line(aes(color=Ano))+
  geom_point(aes(color=Ano))+
  labs(x="Meses",y = "Peso (Kg)"))
}
```

